ALTER TABLE tickets ADD COLUMN IF NOT EXISTS work_status TEXT NOT NULL DEFAULT 'not_started';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS work_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS work_last_resume_at TIMESTAMPTZ;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS work_started_at TIMESTAMPTZ;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS work_completed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS ticket_groups (
  ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  group_id  UUID NOT NULL REFERENCES engineer_groups(id) ON DELETE CASCADE,
  PRIMARY KEY (ticket_id, group_id)
);
